name: firebaseauth
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

